### ISSUE TITLE
Users are able to type invalid values on textboxes

### ISSUE THREAD

**Issue by BrianLima** [zubetto/ColorControl#4]
Users can type non hexadecimal values on the color hex code or type letters freely on R, G or B textboxes.

**Comment by zubetto** [comment]
Incorrect input is filtered out by the _InputComponent_ and the _ColorCodeParser_ methods.
I tried both your handlers and they still need the above filters because user can input exceeded value or paste arbitrary text from a clipboard. _TextBoxPreviewTextInput_ allows to input digits only but it does not check if the input value exceeds 255. _ColorCode_PreviewTextInput_ does not seem to work properly, I can type arbitrary characters.
It would be nice to verify user input by few lines of code, though!
